### ISSUE TITLE
This sim is ready for Interactive Description Implementation

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab#109]
### A11y Features for this sim:
- [x] Keyboard Navigation (except ruler details: shortcut keys, large and small steps)
- [x] Simple Description -  Started: July 23, 2018 ??
- [x] Full Description -  Started: July 23, 2018??; Implementation started October 18, 2018; Description design complete with the Grab,Move, Release responses for the ruler on Nov 28, 2019.
- [x] Sonification - (near complete, similar to GFL Basics with some changes to mass sliders, and an enhanced sound for the moving the ruler)
- [x] Mobile A11y - large range for mass sliders could be a challenge
- [x] RC created -  Jan 27, 2020 - https://github.com/phetsims/QA/issues/471

**Link to [GFL A11y Design Main](https://docs.google.com/document/d/1-37qAgde2XrlXBQae2SgjartM35_EnzDD9pdtd3nXAM/edit)** 

**Implementation of State Descriptions (PDOM)**
- [x] Change [focus order](https://docs.google.com/document/d/1-37qAgde2XrlXBQae2SgjartM35_EnzDD9pdtd3nXAM/edit#heading=h.gamh8gxjx7g5) to match the design document

- **Static State descriptions**
  - [x] Regions, Headings (H1, H2s, H3s)
    - [x] H1 for title
    - [x] H2s for Play Area and Control Area
    - [x] Sim-specific H3s in Play Area and/or Control Area
  - [x] Labels and help text for all interactive items in Play Area
    - [x] Sphere position sliders
    - [x] Mass Controls sliders
    - [x] Measure Distance Ruler (accessible name, aria-roledescription, & help text)
  - [x] Labels and help text for interactive items in Control Area
    - [x] Labels for checkboxes
    - [x] Help text for checkboxes
    - [x] Reset All button
  - [x] Sim Resources (region & H2)
    - [Keyboard Shortcuts Dialog](https://docs.google.com/document/d/1-37qAgde2XrlXBQae2SgjartM35_EnzDD9pdtd3nXAM/edit#heading=h.nnkdju7p2tyn)
      - [x] Visual Keyboard Shortcuts Dialog
      - [x] Keyboard Shortcuts button added
      - [x] Accessible content in Keyboard Shortcuts added
      - [x] Related Interaction hint is in scene/screen summary 

- **Dynamic State descriptions** are ready for PDOM, but only single examples (may need more examples)
  - [x] Dynamic descriptions for the state of the sim (a dynamic list in this case)
  - [x] Dynamic descriptions for Mass Spheres (a dynamic list in this case)
  - [x] Comparable density scale for when Constant Size is checked (implemented in Basics needs verification in Regular)

**Responsive Descriptions (drafted & ready for implementation):**
**[Simple Context Responses ](https://docs.google.com/document/d/1-37qAgde2XrlXBQae2SgjartM35_EnzDD9pdtd3nXAM/edit#heading=h.mp3sseh3ze8h)**
  - [x] Alerts for checking/unchecking checkboxes
  - [x] Reset All alert, verified

**[Complex Object and Context Responses](https://docs.google.com/document/d/1-37qAgde2XrlXBQae2SgjartM35_EnzDD9pdtd3nXAM/edit#heading=h.qvqurriseltj)**
  - Position slider (on focus) 
    - [x] aria-valuetext 
    - [x] brief focus alert read out on focus 
    - [x] edge cases - implemented but needs more work
  - Position sliders increase/decrease information
    - [x] dynamic aria-valuetext (distance and progress)
    - [x] edge cases - implemented but needs work 
  - Mass sliders (on focus) 
      - [x] aria-valuetext
      - [x] brief force alerts read out on focus    
  - Mass sliders: mass increase/decrease information 
    - [x] aria-valuetext (value and comparative size)
    - [x] mass-force increase/decrease alerts
    - [x] edge cases where a mass increase affects position of same or other sphere - implemented and fixed (at least fixed in BASICS)

**Checklist for making Measure Distance Ruler accessible**
- [x] keyboard: native button with `application` role and `aria-roledescription="movable"` on button activation
- [x] gesture: custom (double tap and hold) interaction with `aria-roledescription="movable"` and `aria-describedby` to deliver automatic instructions for first 2 grabs
- [x] platform-specific responses containing specific instructions for first 2 grabs
- [x] general platform-independent responses for grab, move, and releases after initial 2 grabs
  - ready for implementation in #215 
- [x] platform-specific responses for custom keyboard jump shortcuts
  - also ready for implementation in #215

**Update Keyboard Shortcuts Dialog (ready)**
- [x] Updates to Visual dialog (ready for implementation in #214)
- [x] Updates to A11y content for dialog (ready for implementation in #214)

**Check and Update credits before publishing see issue #180**
- [x] Software Development: Michael Barlow, Michael Kauzmann 
- [x] Team: Emily B. Moore, Taliesin Smith, Brianna Tomlinson
- [x] Sound design: Ashton Morris

## Review notes after testing & listening (June 11th)
- [x] don't hear "closest" region see https://github.com/phetsims/a11y-research/issues/146 and closed issue #178
- [x] Scientific Notation checkable again related to PhET-iO - see #207
- [x] Scientific Notation checkbox still checkable when Force Values not checked. It should be disabled in this case - see #110
- [x] Rounding for mass controls see #133 
- [x] New mass sphere descriptions in Play Area #169
- [x] Quantitative distance fro moving the spheres? #156 - yes on "Distance-checked" experience
- [x] No mention of track in screen summary - see issue #159 
- [x] Meter mark heard in m1 description - see updates in #160
- [x] No comparative size in sphere descriptions - see also #160 see also #169 
- [x] Beyond max/min mass mass alerts - see #155 
- [x] List structure around mass controls - see #161 
- [x] Keyboard dialog (size?) - Move Mass Controls block under Move Spheres block - see #144 
- [x] When Force Values in Scientific Notation, I hear “&times”  read out - see #131
- [x] Use “Force vectors” instead of “Vectors” alone when Force Values not checked - see updated  #149. Design doc updated.
- [x] Add Grab button interaction and custom shortcuts - #140

**More on the Ruler Interaction**
- [x] Placement: Grab Ruler comes after Sphere Distance/Position sliders. Should we move it to end of Play Area, or end of Control Area? Yes - see #158 
- [x] Measure Distance Ruler, changed default step to large step and Shift key makes a small step
- [x] Need to make custom shortcuts, alerts, etc.
- [x] Based on what was learned in Friction, what should the Grab button's name/description be. Need to review Grab button for Friction.
- [x] Ruler jumping Keyboard Shortcuts #138 

Edited Nov 29, 2019 - added: items to Ruler section, Keyboard dialog updates, Scientific Notation issue.
Edited Apr 10 - Added Ruler section - no items yet.
Edited Mar 6 - Added Update Credits
Edited Jan 22, 2019: After review updated how items were described, checked off implemented items, added notes where there are implementation issues.
Edited Jan 10, 2019: Added Keyboard Shortcuts Dialog to list
Edited: unchecked Mass slider alerts, and will create issues
Edited: added heading for descriptions.
Edited again: added specific items for PDOM, but not sure if we need this granularity.
Edited again Oct 30: added link to Keyboard Dialog section, adjusted details for the Play Area's interactive items.

**Comment by terracoda** [comment]
@mbarlow12, this is check-list alert to get us started. Please let me know if this works for you. I am excited to work on this sim with you!

**Comment by mbarlow12** [comment]
@terracoda the checklist is great! I've been noticing that QA has done a lot of work with testing/issue templates, and I think we should bring this to the rest of the a11y team to review & refine as a general checklist for implementing these features.

**Comment by mbarlow12** [comment]
@terracoda @emily-phet I've completed work on the screen summary. Moving on to the other PDOM elements later this week.

https://phet-dev.colorado.edu/html/gravity-force-lab/2.2.0-dev.7/phet/gravity-force-lab_en_phet.html?ea&accessibility

https://phet-dev.colorado.edu/html/gravity-force-lab/2.2.0-dev.7/phet/gravity-force-lab_a11y_view.html

**Comment by terracoda** [comment]
@mbarlow12, thanks for the update. I'll check it out.

**Comment by emily-phet** [comment]
@terracoda I'm just seconding that this checklist looks helpful!

**Comment by terracoda** [comment]
Oops, I didn't mean to close the issue, only comment.

**Comment by terracoda** [comment]
@mbarlow12, I've updated the checklist to be more specific. I hope this is helpful.

I've checked off the items that are present in [2.2.0-dev.7](https://phet-dev.colorado.edu/html/gravity-force-lab/2.2.0-dev.7/phet/gravity-force-lab_en_phet.html?ea&accessibility)

**Comment by terracoda** [comment]
Oh, just going to check [dev.8](https://phet-dev.colorado.edu/html/gravity-force-lab/2.2.0-dev.8/phet/gravity-force-lab_en_phet.html?ea&accessibility) now ;-)

**Comment by terracoda** [comment]
@mbarlow12, PDOM is sounding much more complete and the focus order is good.

Any chance you can get an accessible Keyboard Shortcuts button in there, and potentially an accessible Keyboard Shortcuts dialog?

**Comment by terracoda** [comment]
@mbarlow12, on Master I verified that all main PDOM items and the Simple UI alerts are in place. There are still a couple of tweaks to actual content for which I will create new separate issues.

**Comment by terracoda** [comment]
In design meeting Nov 20, @mbarlow12 and I discussed getting started with the Mass changing alerts as they are the least likely to be affected by needed changes to the qualitative scales I drafted.

**Comment by mbarlow12** [comment]
Latest dev release at:
https://phet-dev.colorado.edu/html/gravity-force-lab/2.2.0-dev.11/phet/gravity-force-lab_en_phet.html
and
https://phet-dev.colorado.edu/html/gravity-force-lab/2.2.0-dev.11/phet/gravity-force-lab_a11y_view.html

I believe the `aria-valuetext` content is correct for the mass and position sliders for most if not all edge cases. Alerts for the position sliders also appear to be correct.

The mass controls still have some issues, and focus alerts won't be handled until https://github.com/phetsims/scenery/issues/920 is fixed.

**Comment by terracoda** [comment]
@mbarlow12, thanks for all your hard work and these new links!

**Comment by zepumph** [comment]
@terracoda anything else for this issue?

**Comment by terracoda** [comment]
From my notes in the design doc which I did not add to this issues (apologies). I think everything but #233 has been verified:
- [x] Ruler interaction - changed to Measure Distance Ruler, moveable (done)
- [x] Description Design ready for keyboard and gesture (done)
- [x] Measure Distance Ruler shortcuts (done)
- [x] Measure Distance Ruler essential responses (done) 
- [x] Measure Distance Ruler movement responses (#215) (done) 
- [x] General drag instructions in PDOM (#216) (done) 
- [x] Sonification of Measure Distance Ruler (done)
- [x] Integration of general Sonification design (done - move mass sound to enhanced sounds)
- [x] Changes to PDOM (#240, #207, #218)
- [x] Force Values interaction - changed to radiogroup (closed) #207
- [x] Move Ruler into Play Area after #204 and #207 (closed)
- [ ] #233 - Move responses on iOS - @terracoda to verify today

**Comment by zepumph** [comment]
Awesome! And #233 is now closed. Thanks @terracoda.

**Comment by terracoda** [comment]
I think we can close this issue. Everything in it is implemented, and all things outstanding (a11y related or not) are being tracked in other issues.
